name: Release

on:
  workflow_run:
    workflows: [CI]
    branches: [trunk]
    types: [completed]
  workflow_dispatch:

concurrency: ${{ github.workflow }}

jobs:
  release:
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/shared_release_v1.yaml
    permissions:
      contents: write
